application:
  discord:
    botSecretToken:

sentry:
  dsn: # Intentionally left empty

spring:
  main:
    banner-mode: off
    keep-alive: true # Virtual threads use daemons and JVM exits by default if it has no non-daemon threads
  threads:
    virtual:
      enabled: true # Threads without relying on operating system directly
